### get menu
GET http://localhost:3000/menu
### register
POST http://localhost:3000/register
Content-Type: application/json

{"name":"Gerhard Hager","email":"hager@spengergasse.at","password":"s3cr3t"}
### falscher request ohne payloasd
POST http://localhost:3000/register
Content-Type: application/json
### test hager
POST http://localhost:3000/login
Content-Type: application/x-www-form-urlencoded

email=hager%40spengergasse.at&password=s3cr3t
### test georg
GET http://localhost:3000/test

